# Generated by Django 4.1.7 on 2023-02-24 01:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portafolio", "0002_contact_alter_project_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
